package com.salesforce.loyalty.mobile.myntorewards.viewmodels

enum class EnrollmentState {
    ENROLLMENT_SUCCESS,
    ENROLLMENT_FAILURE,
    ENROLLMENT_DEFAULT_EMPTY,
    ENROLLMENT_IN_PROGRESS
}

enum class ReceiptListScreenPopupState {
    MANUAL_REVIEW,
    RECEIPT_DETAIL,
    RECEIPT_LIST_SCREEN,
}

enum class LoginState {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_IN_PROGRESS,
    LOGIN_DEFAULT_EMPTY,
    LOGIN_SUCCESS_ENROLLMENT_REQUIRED
}

enum class OrderPlacedState {
    ORDER_PLACED_SUCCESS,
    ORDER_PLACED_FAILURE,
    ORDER_PLACED_DEFAULT_EMPTY,
}

enum class PromotionEnrollmentUpdateState {
    PROMOTION_ENROLLMENTUPDATE_SUCCESS,
    PROMOTION_ENROLLMENTUPDATE_FAILURE,
    PROMOTION_ENROLLMENTUPDATE_DEFAULT_EMPTY,
}
enum class LogoutState {
    LOGOUT_IN_PROGRESS,
    LOGOUT_SUCCESS,
    LOGOUT_SUCCESS_AFTER_SESSION_EXPIRY,
    LOGOUT_FAILURE,
    LOGOUT_DEFAULT_EMPTY,
}
