package com.salesforce.loyalty.mobile.myntorewards.utilities

class TestTags {

    companion object {
        const val TEST_TAG_CLOSE_POPUP = "closePopup"
        const val TEST_TAG_PROFILE_ELEMENT_CONTAINER = "ProfileScreenElementContainer"
        const val TEST_TAG_ADDRESS_DETAIL = "address_detail"
        const val TEST_TAG_CHECKOUT_FLOW_CONTAINER = "CheckoutFlowElementContainer"
        const val TEST_TAG_BACK_BUTTON_CHECKOUT_FIRST_SCREEN = "back_button_checkout_first_screen"
        const val TEST_TAG_CHECKOUT_PROMO_NAME = "checkout_promo_name"
        const val TEST_TAG_CHECKOUT_PROMO_DESCRIPTION = "checkout_promo_description"
        const val TEST_TAG_COLLECTION_TYPE = "collection_type"
        const val TEST_TAG_RATING = "rating"
        const val TEST_TAG_ORDER_DESCRIPTION = "order_description"
        const val TEST_TAG_ORDER_IMAGE_SELCTION = "order_image_selection_row"
        const val TEST_TAG_SIZE_SELECTION_ROW = "size_selection_row"
        const val TEST_TAG_SELECT_COLOUR_ROW = "select_colour_row"
        const val TEST_TAG_SELECT_QUANTITY_ROW = "select_quantity_row"
        const val TEST_TAG_PRODUCT_PRICE = "product_price"
        const val TEST_TAG_SHIPPING_PRICE = "shipping_price"
        const val TEST_TAG_SHIPPING_PAYMENT_SCREEN = "shipping_payment_screen"
        const val TEST_TAG_BACK_BUTTON_CHECKOUT_PAYMENT = "back_button_checkout_payment"
        const val TEST_TAG_PAYMENT_UI_CONTAINER = "payment_ui_container"
        const val TEST_TAG_CONFIRM_ORDER_BUTTON = "confirm_order_button"
        const val TEST_TAG_APP_LOGO_HOME_SCREEN = "AppLogoHomeScreen"
        const val TEST_TAG_HOME_SCREEN_CONTAINER = "HomeScreenElementContainer"
        const val TEST_TAG_PROMOTION_CARD = "PromotionCard"
        const val TEST_TAG_VOUCHER_ROW = "VoucherRowView"
        const val TEST_TAG_PROMO_CARD = "promotioncard"
        const val TEST_TAG_BENEFITS = "benefits"
        const val TEST_TAG_QR_CODE = "QR Code"
        const val TEST_TAG_CLICK = " click"
        const val TEST_TAG_TRANSACTION_LIST = "transaction_list"
        const val TEST_TAG_RECENT_TRANSACTION = "recent_transaction"
        const val TEST_TAG_OLD_TRANSACTION = "old_transaction"
        const val TEST_TAG_HOME_SCREEN = "HomeScreen"
        const val TEST_TAG_PROMO_LIST = "promotion_list"
        const val TEST_TAG_PROMO_ITEM = "promo_item"
        const val TEST_TAG_PROMO_POPUP = "promotion_popup"
        const val TEST_TAG_CLOSE_POPUP_PROMOTION = "close_button"
        const val TEST_TAG_PROMO_NAME = "promo_name"
        const val TEST_TAG_DETAIL_HEADING = "detail_heading"
        const val TEST_TAG_PROMO_DESCRIPTION = "promo_description"
        const val TEST_TAG_EXPIRATION_DATE = "expiration_date"
        const val TEST_TAG_EMAIL_PHONE = "EmailID_PhoneNumber"
        const val TEST_TAG_ENROLLMENT_CONGRATULATIONS = "EnrollmentCongratsScreenTag"
        const val TEST_TAG_JOIN_UI = "JoinUI"
        const val TEST_TAG_JOIN_BUTTON = "JoinButton"
        const val TEST_TAG_LOGIN_UI = "LoginUI"

        //receipt
        const val TEST_TAG_RECEIPT_LIST_SCREEN = "ReceiptList"
        const val TEST_TAG_SEARCH_FIELD = "SearchField"
        const val TEST_TAG_RECEIPT_LIST = "Receipt_List"
        const val TEST_TAG_RECEIPT_LIST_ITEM = "Receipt_List_Item"
        const val TEST_TAG_CAMERA_SCREEN = "CAMERA_SCREEN"
        const val TEST_TAG_CAMERA = "CAMERA"
        const val TEST_TAG_IMAGE_PREVIEW_SCREEN = "Image_Preview_Screen"
        const val TEST_TAG_RECEIPT_PROCESS_SCREEN = "receipt_process_screen"
        const val TEST_TAG_RECEIPT_TABLE_SCREEN = "receipt_table_screen"
        const val TEST_TAG_ROW_STORE_DETAILS = "row_store_details"
        const val TEST_TAG_RECEIPT_TABLE = "receipt_table"
        const val TEST_TAG_CONGRATULATIONS_SCREEN = "congratulations_screen"
        const val TEST_TAG_TRY_AGAIN_SCANNED_RECEIPT = "screened_receipt-try_again_button"
        const val TEST_TAG_TRY_AGAIN_ERROR_SCREEN = "error_screen_try_again_button"
        const val TEST_TAG_ERROR_SCREEN = "error_screen_tag"
        const val MY_PROMOTION_FULL_SCREEN_HEADER = "my_promotion_header"
        const val MY_PROFILE_FULL_SCREEN_HEADER = "my_profile_header"
        const val MORE_FULL_SCREEN_HEADER = "more_header"
        const val TEST_TAG_CHECKOUT_DELIVER_TO_ADDRESS = "checkout_deliver_to_address_button"
        const val TEST_TAG_CHECKOUT_ADD_TO_CART ="checkout_add_to_cart_button"
        const val TEST_TAG_MANUAL_REVIEW_CLOSE_POPUP_ICON ="manual_review_closepopup_icon"
        const val TEST_TAG_MANUAL_REVIEW_HEADER ="manual_review_header"
        const val TEST_TAG_MANUAL_RECEIPT_NUMBER ="manual_review_receipt_number"
        const val TEST_TAG_MANUAL_RECEIPT_DATE ="manual_review_receipt_date"
        const val TEST_TAG_MANUAL_RECEIPT_POINT ="manual_review_receipt_point"
        const val TEST_TAG_MANUAL_RECEIPT_COMMENT ="manual_review_receipt_comment"
        const val TEST_TAG_MANUAL_SUBMIT_BUTTON ="manual_review_submit_button"
        const val TEST_TAG_MANUAL_BACK_BUTTON = "manual_review_back_button"
        const val TEST_TAG_RECEIPT_STATUS = "receiptStatus"
        const val TEST_TAG_RECEIPT_DETAIL_SCREEN = "receipt_detail_screen"
        const val TEST_TAG_RECEIPT_NUMBER= "receiptNumber"
        const val TEST_TAG_RECEIPT_DATE= "receiptDate"
        const val TEST_TAG_RECEIPT_DETAIL_BACK_BUTTON= "receipt_detail_back_button"
        const val TEST_TAG_RECEIPT_UPLOAD= "UploadReceipt"
        const val TEST_TAG_HOME_SCREEN_SUBHEADER_PROMOTION= "MyPromotionTag"
        const val TEST_TAG_GAME_ZONE_ITEM= "game_zone_item"
        const val TEST_TAG_GAME_ZONE_ITEM_IMAGE= "game_zone_item_image"
        const val TEST_TAG_GAME_ZONE_ITEM_TITLE= "game_zone_item_title"
        const val TEST_TAG_GAME_ZONE_ITEM_TYPE= "game_zone_item_sub_type"
        const val TEST_TAG_GAME_ZONE_ITEM_EXPIRY= "game_zone_item_sub_expiry"
        const val TEST_TAG_SPIN_WHEEL_BG= "spin_wheel_bg"
        const val TEST_TAG_SPIN_WHEEL_HEADER= "spin_wheel_header"
        const val TEST_TAG_SPIN_WHEEL_CIRCLE= "spin_wheel_circle"
        const val TEST_TAG_SPIN_WHEEL_FRAME= "spin_wheel_frame"
        const val TEST_TAG_SPIN_WHEEL_COLOUR_SEGMENT= "spin_wheel_segment"
        const val TEST_TAG_SPIN_WHEEL_CONTENT= "spin_wheel_content"
        const val TEST_TAG_SPIN_WHEEL_POINTER= "spin_wheel_pointer"
        const val TEST_TAG_SPIN_WHEEL_FOOTER= "spin_wheel_footer"
        const val TEST_TAG_GAME_ZONE_SCREEN="game_zone_screen"
        const val TEST_TAG_SPIN_WHEEL_TEXT="spin_wheel_text"
        const val TEST_TAG_GAME_PLAYED_SCREEN="game_played_screen"
        const val TEST_TAG_GAME_PLAYED_CONFIRMATION_SCREEN="game_played_confirmation_screen"
        const val TEST_TAG_SCRATCH_CARD_SCREEN="scratch_card_screen"
        const val TEST_TAG_SUBHEADER_CONGRATS_SCREEN="subheader_congrats_screen"
        const val TEST_TAG_SCRATCH_CARD="scratch_card"


        const val TEST_TAG_RECEIPT_FIRST_STEP_COMPLETED= "first_step_completed"
        const val TEST_TAG_RECEIPT_SECOND_STEP_COMPLETED= "second_step_completed"
    }
}