package com.salesforce.loyalty.mobile.myntorewards.utilities

class TestTags {

    companion object {
        const val TEST_TAG_CLOSE_POPUP = "closePopup"
        const val TEST_TAG_PROFILE_ELEMENT_CONTAINER = "ProfileScreenElementContainer"
        const val TEST_TAG_ADDRESS_DETAIL = "address_detail"
        const val TEST_TAG_CHECKOUT_FLOW_CONTAINER = "CheckoutFlowElementContainer"
        const val TEST_TAG_BACK_BUTTON_CHECKOUT_FIRST_SCREEN = "back_button_checkout_first_screen"
        const val TEST_TAG_CHECKOUT_PROMO_NAME = "checkout_promo_name"
        const val TEST_TAG_CHECKOUT_PROMO_DESCRIPTION = "checkout_promo_description"
        const val TEST_TAG_COLLECTION_TYPE = "collection_type"
        const val TEST_TAG_RATING = "rating"
        const val TEST_TAG_ORDER_DESCRIPTION = "order_description"
        const val TEST_TAG_ORDER_IMAGE_SELCTION = "order_image_selection_row"
        const val TEST_TAG_SIZE_SELECTION_ROW = "size_selection_row"
        const val TEST_TAG_SELECT_COLOUR_ROW = "select_colour_row"
        const val TEST_TAG_SELECT_QUANTITY_ROW = "select_quantity_row"
        const val TEST_TAG_PRODUCT_PRICE = "product_price"
        const val TEST_TAG_SHIPPING_PRICE = "shipping_price"
        const val TEST_TAG_SHIPPING_PAYMENT_SCREEN = "shipping_payment_screen"
        const val TEST_TAG_BACK_BUTTON_CHECKOUT_PAYMENT= "back_button_checkout_payment"
        const val TEST_TAG_PAYMENT_UI_CONTAINER= "payment_ui_container"
        const val TEST_TAG_CONFIRM_ORDER_BUTTON= "confirm_order_button"
        const val TEST_TAG_APP_LOGO_HOME_SCREEN="AppLogoHomeScreen"
        const val TEST_TAG_HOME_SCREEN_CONTAINER="HomeScreenElementContainer"
        const val TEST_TAG_PROMOTION_CARD="PromotionCard"
        const val TEST_TAG_VOUCHER_ROW="VoucherRowView"
        const val TEST_TAG_PROMO_CARD="promotioncard"
        const val TEST_TAG_BENEFITS="benefits"
        const val TEST_TAG_QR_CODE="QR Code"
        const val TEST_TAG_CLICK=" click"
        const val TEST_TAG_TRANSACTION_LIST="transaction_list"
        const val TEST_TAG_RECENT_TRANSACTION="recent_transaction"
        const val TEST_TAG_HOME_SCREEN="HomeScreen"
        const val TEST_TAG_PROMO_LIST="promotion_list"
        const val TEST_TAG_PROMO_ITEM="promo_item"
        const val TEST_TAG_PROMO_POPUP="promotion_popup"
        const val TEST_TAG_CLOSE_POPUP_PROMOTION="close_button"
        const val TEST_TAG_PROMO_NAME="promo_name"
        const val TEST_TAG_DETAIL_HEADING="detail_heading"
        const val TEST_TAG_PROMO_DESCRIPTION="promo_description"
        const val TEST_TAG_EXPIRATION_DATE="expiration_date"
        const val TEST_TAG_EMAIL_PHONE="EmailID_PhoneNumber"
        const val TEST_TAG_ENROLLMENT_CONGRATULATIONS="EnrollmentCongratsScreenTag"
        const val TEST_TAG_JOIN_UI="JoinUI"
        const val TEST_TAG_JOIN_BUTTON="JoinButton"
        const val TEST_TAG_LOGIN_UI="LoginUI"

    }
}